### ISSUE TITLE
Train.py works but not train_multigpu.py

### ISSUE THREAD

**Issue by developeralgo8888** [zhongwen/predictron#11]
I used train.py and that works without any issues but train_multigpu.py throws an error at the following line as indicated in my earlier issue

# Apply the gradients to adjust the shared variables.
    apply_gradient_op = opt.apply_gradients(grad_vars, global_step=global_step)

# ERROR#

Traceback (most recent call last):
  File "./train_multigpu.py", line 253, in <module>
    tf.app.run()
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_multigpu.py", line 249, in main
    train()
  File "./train_multigpu.py", line 183, in train
    **apply_gradient_op = opt.apply_gradients(grad_vars, global_step=global_step)**
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 409, in apply_gradients
    self._create_slots(var_list)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/adam.py", line 119, in _create_slots
    self._zeros_slot(v, "m", self._name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 609, in _zeros_slot
    named_slots[var] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 123, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 101, in create_slot
    return _create_slot_var(primary, val, '')
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/slot_creator.py", line 55, in _create_slot_var
    slot = variable_scope.get_variable(scope, initializer=val, trainable=False)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 988, in get_variable
    custom_getter=custom_getter)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 890, in get_variable
    custom_getter=custom_getter)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 348, in get_variable
    validate_shape=validate_shape)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 333, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 657, in _get_single_variable
    "VarScope?" % name)
**ValueError: Variable state/conv1/weights/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?**

**Comment by zhongwen** [comment]
I am on vacation for Spring Festival now. 

As discussed in previous issues, please try to fix it if you insist to use a different version. I really recommend you did it in r0.12.1 and obviously you were not running the same version as I mentioned.

**Comment by developeralgo8888** [comment]
I am using exactly same version as you indicated earlier

TF = r0.12.1
Python = 3.5
